set firewall all-ping 'enable'
set firewall broadcast-ping 'disable'
set firewall config-trap 'disable'
set firewall ipv6-receive-redirects 'disable'
set firewall ipv6-src-route 'disable'
set firewall ip-src-route 'disable'
set firewall log-martians 'enable'
set firewall name LAN-to-OPT default-action 'drop'
set firewall name LAN-to-OPT enable-default-log
set firewall name LAN-to-OPT rule 2 action 'accept'
set firewall name LAN-to-WAN default-action 'drop'
set firewall name LAN-to-WAN enable-default-log
set firewall name LAN-to-WAN rule 10 action 'accept'
set firewall name LAN-to-WAN rule 10 destination port '80'
set firewall name LAN-to-WAN rule 10 protocol 'udp'
set firewall name LAN-to-WAN rule 30 action 'accept'
set firewall name LAN-to-WAN rule 30 protocol 'icmp'
set firewall name LAN-to-WAN rule 40 action 'accept'
set firewall name OPT-to-LAN default-action 'drop'
set firewall name OPT-to-LAN enable-default-log
set firewall name OPT-to-LAN rule 2 action 'accept'
set firewall name OPT-to-WAN default-action 'drop'
set firewall name OPT-to-WAN enable-default-log
set firewall name OPT-to-WAN rule 1 action 'accept'
set firewall name OPT-to-WAN rule 1 state established 'enable'
set firewall name OPT-to-WAN rule 10 action 'accept'
set firewall name OPT-to-WAN rule 10 destination port '80'
set firewall name OPT-to-WAN rule 10 protocol 'tcp'
set firewall name OPT-to-WAN rule 30 action 'accept'
set firewall name OPT-to-WAN rule 30 protocol 'icmp'
set firewall name WAN-to-LAN default-action 'drop'
set firewall name WAN-to-LAN enable-default-log
set firewall name WAN-to-LAN rule 1 action 'accept'
set firewall name WAN-to-LAN rule 1 state established 'enable'
set firewall name WAN-to-LAN rule 10 action 'accept'
set firewall name WAN-to-LAN rule 10 destination port '80'
set firewall name WAN-to-LAN rule 10 protocol 'tcp'
set firewall name WAN-to-OPT default-action 'drop'
set firewall name WAN-to-OPT enable-default-log
set firewall name WAN-to-OPT rule 1 action 'accept'
set firewall name WAN-to-OPT rule 1 state established 'enable'
set firewall name WAN-to-OPT rule 10 action 'accept'
set firewall name WAN-to-OPT rule 10 destination port '80'
set firewall name WAN-to-OPT rule 10 protocol 'tcp'
set firewall name WAN-to-OPT rule 20 action 'accept'
set firewall name WAN-to-OPT rule 20 destination port '22'
set firewall name WAN-to-OPT rule 20 protocol 'tcp'
set firewall receive-redirects 'disable'
set firewall send-redirects 'enable'
set firewall source-validation 'disable'
set firewall syn-cookies 'enable'
set firewall twa-hazards-protection 'disable'
set high-availability vrrp group langroup12 interface 'eth1'
set high-availability vrrp group langroup12 priority '5'
set high-availability vrrp group langroup12 virtual-address '10.0.5.1/24'
set high-availability vrrp group langroup12 vrid '10'
set high-availability vrrp group optgroup12 interface 'eth2'
set high-availability vrrp group optgroup12 priority '5'
set high-availability vrrp group optgroup12 virtual-address '10.0.6.1/24'
set high-availability vrrp group optgroup12 vrid '20'
set high-availability vrrp group wangroup12 interface 'eth0'
set high-availability vrrp group wangroup12 priority '5'
set high-availability vrrp group wangroup12 virtual-address '10.0.17.82/24'
set high-availability vrrp group wangroup12 vrid '162'
set interfaces ethernet eth0 address '10.0.17.62/24'
set interfaces ethernet eth0 description 'WAN'
set interfaces ethernet eth0 hw-id '00:50:56:b3:49:5f'
set interfaces ethernet eth1 address '10.0.5.3/24'
set interfaces ethernet eth1 description 'LAN'
set interfaces ethernet eth1 hw-id '00:50:56:b3:a4:89'
set interfaces ethernet eth2 address '10.0.6.3/24'
set interfaces ethernet eth2 description 'OPT'
set interfaces ethernet eth2 hw-id '00:50:56:b3:50:b2'
set interfaces loopback lo
set nat destination rule 10 description 'web traffic to web01'
set nat destination rule 10 destination port '80'
set nat destination rule 10 inbound-interface 'eth0'
set nat destination rule 10 protocol 'tcp'
set nat destination rule 10 translation address '10.0.6.39'
set nat destination rule 20 description 'ssh traffic to web01'
set nat destination rule 20 destination port '22'
set nat destination rule 20 inbound-interface 'eth0'
set nat destination rule 20 protocol 'tcp'
set nat destination rule 20 translation address '10.0.6.100'
set nat source rule 10 description 'NAT from OPT to WAN'
set nat source rule 10 outbound-interface 'eth0'
set nat source rule 10 source address '10.0.6.0/24'
set nat source rule 10 translation address 'masquerade'
set nat source rule 15 description 'NAT from LAN to WAN'
set nat source rule 15 outbound-interface 'eth0'
set nat source rule 15 source address '10.0.5.0/24'
set nat source rule 15 translation address 'masquerade'
set protocols static route 0.0.0.0/0 next-hop 10.0.17.2
set service dns forwarding allow-from '10.0.6.0/24'
set service dns forwarding allow-from '10.0.5.0/24'
set service dns forwarding listen-address '10.0.6.3'
set service dns forwarding listen-address '10.0.5.3'
set service dns forwarding listen-address '10.0.5.1'
set service dns forwarding listen-address '10.0.6.1'
set service ssh listen-address '0.0.0.0'
set system config-management commit-revisions '100'
set system console device ttyS0 speed '115200'
set system host-name 'vyos'
set system login user vyos authentication encrypted-password '$6$lEgayS1Fn7$Y4.VS/yBAdhxkmgDAzrzUN/ibgmO9rRgblmnMMxvFqN1D89m/XTqRxk7.DW60cj5Dvv9PC5c0n0V3M7weIk9v/'
set system login user vyos authentication plaintext-password ''
set system name-server '10.0.17.2'
set system ntp server 0.pool.ntp.org
set system ntp server 1.pool.ntp.org
set system ntp server 2.pool.ntp.org
set system syslog global facility all level 'info'
set system syslog global facility protocols level 'debug'
set zone-policy zone LAN default-action 'drop'
set zone-policy zone LAN from OPT firewall name 'OPT-to-LAN'
set zone-policy zone LAN from WAN firewall name 'WAN-to-LAN'
set zone-policy zone LAN interface 'eth1'
set zone-policy zone OPT default-action 'drop'
set zone-policy zone OPT from LAN firewall name 'LAN-to-OPT'
set zone-policy zone OPT from WAN firewall name 'WAN-to-OPT'
set zone-policy zone OPT interface 'eth2'
set zone-policy zone WAN default-action 'drop'
set zone-policy zone WAN from LAN firewall name 'LAN-to-WAN'
set zone-policy zone WAN from OPT firewall name 'OPT-to-WAN'
set zone-policy zone WAN interface 'eth0'
